spring:
  jpa:
    properties.hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  sql.init.mode: always
  threads.virtual.enabled: true
springdoc:
  api-docs.enabled: false
  swagger-ui.url: /open-api.json
  show-actuator: true