spring:
  jpa:
    properties.hibernate.format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
  sql.init.mode: always
