CREATE TABLE IF NOT EXISTS "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(255) NOT NULL,
  "total_amount" double precision,
  "created_on" timestamp NOT NULL DEFAULT now(),
  "last_updated_on" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(255),
  "quantity" integer NOT NULL DEFAULT 0,
  "price" double precision NOT NULL,
  "created_on" timestamp NOT NULL DEFAULT now(),
  "last_updated_on" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "order_product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "product_id" integer,
  UNIQUE ("order_id", "product_id"),
  CONSTRAINT "fk_order"
      FOREIGN KEY("order_id")
          REFERENCES "order" ("id"),
  CONSTRAINT "fk_product"
      FOREIGN KEY("product_id")
          REFERENCES "product" ("id")
);
