CREATE TABLE IF NOT EXISTS "product" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(255) UNIQUE NOT NULL,
    "description" varchar(255),
    "quantity" integer NOT NULL DEFAULT 0,
    "price" double precision NOT NULL,
    "last_update" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "order" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "description" varchar(255),
    "total_amount" double precision NOT NULL,
    "last_update" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "order_product" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" integer,
    "order_id" integer
);

CREATE UNIQUE INDEX ON "order_product" ("product_id", "order_id");

ALTER TABLE IF EXISTS "order_product" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");
ALTER TABLE IF EXISTS "order_product" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id");
