CREATE TABLE IF NOT EXISTS "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(255),
  "total_amount" float NOT NULL,
  "last_update" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "description" varchar(255),
  "quantity" integer NOT NULL DEFAULT 0,
  "price" float NOT NULL,
  "last_update" timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "order_products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer,
  "product_id" integer
);

CREATE UNIQUE INDEX IF NOT EXISTS ON "order_products" ("product_id", "order_id");

ALTER TABLE IF EXISTS "orders" ADD FOREIGN KEY ("id") REFERENCES "order_products" ("order_id");

ALTER TABLE IF EXISTS "products" ADD FOREIGN KEY ("id") REFERENCES "order_products" ("product_id");
